# Load settings shared with the popup server (see tmux-popup.sh / tmux-popup.conf)
source-file ~/.config/tmux/tmux-shared.conf

# Open a popup window
bind P display-popup -E -d '#{pane_current_path}' -w 100% -h 100% "$HOME/.local/bin/tmux-popup.sh"
